version: 1.0.0.{build}
image: Visual Studio 2019

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
- ps: dotnet publish -c Release -r win-x64 Flow.Launcher.Plugin.QrCodeGenerator/Flow.Launcher.Plugin.QrCodeGenerator.csproj

after_build:
- ps: >-
    Copy-Item -Path Flow.Launcher.Plugin.QrCodeGenerator/icon.png -Destination Flow.Launcher.Plugin.QrCodeGenerator/bin/Release/win-x64/publish/icon.png

    Compress-Archive -Path "Flow.Launcher.Plugin.QrCodeGenerator\bin\Release\win-x64\publish\*" -DestinationPath "plugin.zip"

    Rename-Item plugin.zip Flow.Launcher.Plugin.QrCodeGenerator.flowlauncher

artifacts:
    - path: 'Flow.Launcher.Plugin.QrCodeGenerator.flowlauncher'