name: Build windows plugin package

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: public win x64
      run: dotnet publish Flow.Launcher.Plugin.QrCodeGenerator -c Release -r win-x64
      
    - name: copy icon
      run: Copy-Item -Path Flow.Launcher.Plugin.QrCodeGenerator/icon.png -Destination Flow.Launcher.Plugin.QrCodeGenerator/bin/Release/win-x64/publish/icon.png

    - name: zip plugin package
      run: Compress-Archive -LiteralPath Flow.Launcher.Plugin.QrCodeGenerator/bin/Release/win-x64/publish -DestinationPath Flow.Launcher.Plugin.QrCodeGenerator/bin/QrCodeGenerator-win-x64.zip -Force

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: QrCodeGenerator-win-x64
        path: Flow.Launcher.Plugin.QrCodeGenerator/bin/QrCodeGenerator-win-x64.zip

    - name: Release artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Flow.Launcher.Plugin.QrCodeGenerator/bin/QrCodeGenerator-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}